# Generated by rust2rpm 11
%bcond_without check
%global debug_package %{nil}

%global crate mio

Name:           rust-%{crate}
Version:        0.6.21
Release:        2%{?dist}
Summary:        Lightweight non-blocking IO

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/mio
Source:         %{crates_source}
# Initial patched metadata
# * No windows or fuchsia
Patch0:         mio-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Lightweight non-blocking IO.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version}/
%exclude %{cargo_registry}/%{crate}-%{version}/{azure-pipelines.yml,.cirrus.yml,ci}

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+with-deprecated-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-deprecated-devel %{_description}

This package contains library source intended for building other packages
which use "with-deprecated" feature of "%{crate}" crate.

%files       -n %{name}+with-deprecated-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.6.21-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Tue Dec 10 2019 Josh Stone <jistone@redhat.com> - 0.6.21-1
- Update to 0.6.21

* Fri Nov 22 2019 Josh Stone <jistone@redhat.com> - 0.6.20-1
- Update to 0.6.20

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.6.19-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Fri Jun 21 21:27:15 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.19-2
- Regenerate

* Sat Jun 01 2019 Josh Stone <jistone@redhat.com> - 0.6.19-1
- Update to 0.6.19

* Sun Feb 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.16-3
- Adapt to new packaging

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.6.16-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Sat Sep 08 2018 Josh Stone <jistone@redhat.com> - 0.6.16-1
- Update to 0.6.16

* Sat Jul 14 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.6.15-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Wed Jul 11 2018 Josh Stone <jistone@redhat.com> - 0.6.15-1
- Update to 0.6.15

* Fri Jun 15 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.14-2
- Bump lazycell to 1

* Fri Mar 09 2018 Josh Stone <jistone@redhat.com> - 0.6.14-1
- Update to 0.6.14

* Wed Feb 07 2018 Josh Stone <jistone@redhat.com> - 0.6.13-1
- Update to 0.6.13

* Wed Jan 10 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.12-1
- Update to 0.6.12

* Fri Dec 01 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.11-1
- Update to 0.6.11

* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.9-1
- Initial package
